export const titles: Record<string, string> = {
  '/welcome': 'Welcome',
  '/more-blocks': 'More Blocks',
  '/home': 'Home',
  '/': 'Home',
  '/admin': 'Admin',
  '/admin.sub-page': 'Sub-Page',
  '/login': 'Login',
  '/register': 'Register',
  '/register-result': 'Register Result',
  '/dashboard': 'Dashboard',
  '/dashboard/analysis': 'Analysis',
  '/dashboard/monitor': 'Monitor',
  '/dashboard/workplace': 'Workplace',
  '/exception/403': '403',
  '/exception/404': '404',
  '/exception/500': '500',
  '/form': 'Form',
  '/form/basic-form': 'Basic Form',
  '/form/step-form': 'Step Form',
  '/form/step-form/info': 'Step Form(write transfer information)',
  '/form/step-form/confirm': 'Step Form(confirm transfer information)',
  '/form/step-form/result': 'Step Form(finished)',
  '/form/advanced-form': 'Advanced Form',
  '/list': 'List',
  '/list/table-list': 'Search Table',
  '/list/basic-list': 'Basic List',
  '/list/card-list': 'Card List',
  '/list/search-list': 'Search List',
  '/list/search-list/articles': 'Search List(articles)',
  '/list/search-list/projects': 'Search List(projects)',
  '/list/search-list/applications': 'Search List(applications)',
  '/profile': 'Profile',
  '/profile/basic': 'Basic Profile',
  '/profile/advanced': 'Advanced Profile',
  '/result': 'Result',
  '/result/success': 'Success',
  '/result/fail': 'Fail',
  '/exception': 'Exception',
  '/exception/not-permission': '403',
  '/exception/not-find': '404',
  '/exception/server-error': '500',
  '/exception/trigger': 'Trigger',
  '/account': 'Account',
  '/account/center': 'Account Center',
  '/account/settings': 'Account Settings',
  '/account/trigger': 'Trigger Error',
  '/account/logout': 'Logout',
  '/editor': 'Graphic Editor',
  '/editor/flow': 'Flow Editor',
  '/editor/mind': 'Mind Editor',
  '/editor/koni': 'Koni Editor',
  '/system': 'system',
  '/system/user': 'user manager',
  '/testMenu/chart': 'chart',
};

export default titles;
